-- Seed data for local development
-- Run with: npm run db:seed:local

-- ============================================================
-- Tracking Settings (single-row config)
-- ============================================================

INSERT OR REPLACE INTO tracking_settings (
  id, meta_pixel_enabled, meta_pixel_id, meta_capi_enabled, meta_capi_token,
  ga_enabled, ga_measurement_id, ga_mp_enabled, ga_mp_api_secret,
  gtm_enabled, gtm_container_id,
  utm_tracking_enabled, cookie_consent_enabled
) VALUES (
  1, 1, '1234567890123456', 1, 'TEST_CAPI_TOKEN_FOR_E2E',
  1, 'G-TESTDEV001', 1, 'test-mp-api-secret',
  1, 'GTM-TEST001',
  1, 0
);

-- ============================================================
-- Site Settings (single-row config)
-- ============================================================

INSERT OR REPLACE INTO site_settings (
  id, name, description, author,
  social, product_links, features, ui, theme, logo_url, announcement
) VALUES (
  1, 'Product Name', 'One-line value proposition for your product.', 'Company Name',
  '{"twitter":"","github":"","discord":"","instagram":""}',
  '{"appUrl":"","appStoreUrl":"","playStoreUrl":""}',
  '{"waitlist":true,"giveaway":true,"blog":true,"contact":true,"pricing":false,"changelog":false}',
  '{"search":true,"themeToggle":true}',
  '{"preset":"bold","accentColor":"#9747ff","borderRadius":"0.625rem","headingWeight":"400","fontFamily":"inter","heroVariant":"gradient","headerVariant":"blur","footerVariant":"simple","postCardVariant":"bordered","ctaSectionVariant":"gradient"}',
  NULL,
  '{"enabled":false,"text":"","linkUrl":"","linkText":""}'
);

-- ============================================================
-- System Pages (9 rows) — now with layout column
-- ============================================================

INSERT OR REPLACE INTO pages (slug, parent_slug, title, description, content, faqs, related_pages, cover_image, metadata, layout, published, sort_order, updated_at) VALUES
('home', NULL, 'Home', 'Welcome to our product — the best way to solve your problem.', NULL,
  '[{"question":"What is this product?","answer":"A tool designed to help you launch and grow your product faster."},{"question":"When does it launch?","answer":"We are currently in pre-launch. Join the waitlist to be the first to know!"},{"question":"Is the waiting list free?","answer":"Yes, signing up for the waiting list is completely free."}]',
  '[{"title":"Join the Waitlist","description":"Be the first to get access.","href":"/waitlist"},{"title":"Read the Blog","description":"Tips and insights from our team.","href":"/blog"}]',
  NULL, NULL, 'default', 1, 0, datetime('now')),

('waitlist', NULL, 'Waitlist', 'Join our waiting list and be the first to get access.',
  '[{"type":"heading","text":"Join the Waiting List","level":2},{"type":"paragraph","text":"Sign up below to reserve your spot. Each referral moves you up the list!"}]',
  '[{"question":"How does the referral system work?","answer":"Share your unique referral link. Each friend who signs up moves you 5 positions up the list."},{"question":"When will I get access?","answer":"We will send invites in order of position. Early signups and active referrers get access first."},{"question":"Can I sign up more than once?","answer":"No, each email can only be registered once. If you try again, we will show your existing dashboard."}]',
  '[{"title":"Enter the Giveaway","description":"Win prizes while you wait.","href":"/giveaway"},{"title":"Read the Blog","description":"Stay updated with our latest posts.","href":"/blog"}]',
  NULL, '{"boostFactor":5}', 'default', 1, 1, datetime('now')),

('giveaway', NULL, 'Giveaway', 'Enter our giveaway for a chance to win amazing prizes.',
  '[{"type":"heading","text":"Enter the Giveaway","level":2},{"type":"paragraph","text":"Complete actions below for bonus entries. The more entries, the better your chances!"}]',
  '[{"question":"How do bonus entries work?","answer":"Each completed action (sharing, following, referring) gives you extra entries into the draw."},{"question":"When is the giveaway drawn?","answer":"The draw will happen on the end date shown on the page. Winners will be notified by email."},{"question":"Who is eligible?","answer":"Anyone who enters before the end date. You must be 18 or older."}]',
  '[{"title":"Join the Waitlist","description":"Get early access to the product.","href":"/waitlist"},{"title":"Read the Blog","description":"Learn more about what we are building.","href":"/blog"}]',
  NULL, '{"endDate":"2026-12-31T00:00:00Z","prizeTitle":"Premium Lifetime Access","prizeDescription":"Win a lifetime premium subscription.","bonusEntries":{"share":3,"follow":2,"referral":5}}', 'default', 1, 2, datetime('now')),

('contact', NULL, 'Contact', 'Get in touch with our team.',
  '[{"type":"heading","text":"Contact Us","level":2},{"type":"paragraph","text":"Have a question, partnership inquiry, or just want to say hi? Fill out the form below."}]',
  '[{"question":"How long until I hear back?","answer":"We typically respond within 24-48 hours on business days."},{"question":"Can I partner with you?","answer":"Absolutely! Use the contact form and mention partnership in your message."}]',
  '[{"title":"Join the Waitlist","description":"Sign up for early access.","href":"/waitlist"},{"title":"Read the Blog","description":"Check out our latest updates.","href":"/blog"}]',
  NULL, NULL, 'default', 1, 3, datetime('now')),

('blog', NULL, 'Blog', 'Insights, tutorials, and updates from our team.', NULL,
  NULL, NULL, NULL, NULL, 'default', 1, 4, datetime('now')),

('terms', NULL, 'Terms of Use', 'Terms of use for our product and services.',
  '[{"type":"heading","text":"Terms of Use","level":2},{"type":"paragraph","text":"By using our services, you agree to these terms. Please read them carefully."},{"type":"heading","text":"1. Acceptance of Terms","level":3},{"type":"paragraph","text":"By accessing or using our service, you agree to be bound by these Terms of Use and our Privacy Policy."},{"type":"heading","text":"2. Use of Service","level":3},{"type":"paragraph","text":"You may use our service only for lawful purposes and in accordance with these terms."},{"type":"heading","text":"3. Intellectual Property","level":3},{"type":"paragraph","text":"All content and materials available on the service are the property of the company."}]',
  NULL, NULL, NULL, NULL, 'default', 1, 5, datetime('now')),

('privacy', NULL, 'Privacy Policy', 'How we collect, use, and protect your data.',
  '[{"type":"heading","text":"Privacy Policy","level":2},{"type":"paragraph","text":"Your privacy is important to us. This policy explains how we handle your personal information."},{"type":"heading","text":"1. Information We Collect","level":3},{"type":"paragraph","text":"We collect information you provide directly, such as your name and email address when you sign up for the waitlist."},{"type":"heading","text":"2. How We Use Information","level":3},{"type":"paragraph","text":"We use your information to provide and improve our services, send you updates, and communicate with you."},{"type":"heading","text":"3. Data Security","level":3},{"type":"paragraph","text":"We implement appropriate security measures to protect your personal information."}]',
  NULL, NULL, NULL, NULL, 'default', 1, 6, datetime('now')),

('pricing', NULL, 'Pricing', 'Simple, transparent pricing for every stage of growth.',
  '[{"type":"heading","text":"Simple Pricing","level":2},{"type":"paragraph","text":"Choose the plan that fits your needs. No hidden fees, cancel anytime."}]',
  '[{"question":"Can I change plans later?","answer":"Yes, you can upgrade or downgrade at any time. Changes take effect on your next billing cycle."},{"question":"Is there a free trial?","answer":"Yes, all paid plans include a 14-day free trial with full access to features."},{"question":"Do you offer refunds?","answer":"Yes, we offer a 30-day money-back guarantee on all plans."}]',
  '[{"title":"Join the Waitlist","description":"Get early access and special pricing.","href":"/waitlist"},{"title":"Contact Us","description":"Have questions? Get in touch.","href":"/contact"}]',
  NULL, '{"tiers":[{"name":"Free","price":"$0","period":"forever","description":"Get started with the basics.","features":["Up to 3 projects","Basic analytics","Community support"],"cta":"Get Started","ctaUrl":"/waitlist","highlighted":false},{"name":"Pro","price":"$19","period":"/month","description":"Everything you need to grow.","features":["Unlimited projects","Advanced analytics","Priority support","Custom integrations","API access"],"cta":"Start Free Trial","ctaUrl":"/waitlist","highlighted":true},{"name":"Enterprise","price":"Custom","period":"","description":"For large teams and organizations.","features":["Everything in Pro","Dedicated account manager","SSO & SAML","Custom SLA","On-premise option"],"cta":"Contact Sales","ctaUrl":"/contact","highlighted":false}]}', 'default', 1, 7, datetime('now')),

('changelog', NULL, 'Changelog', 'Stay up to date with the latest product updates and improvements.',
  '[{"type":"heading","text":"Changelog","level":2},{"type":"paragraph","text":"Track all the latest updates, improvements, and bug fixes."}]',
  '[{"question":"How often do you release updates?","answer":"We ship updates weekly, with major releases approximately once a month."},{"question":"Can I request a feature?","answer":"Absolutely! Use our contact form to submit feature requests."}]',
  '[{"title":"Read the Blog","description":"In-depth articles about our latest features.","href":"/blog"},{"title":"Contact Us","description":"Have feedback? Let us know.","href":"/contact"}]',
  NULL, '{"entries":[{"date":"2026-03-01","title":"Launch Announcement","description":"We are excited to announce the launch of our product!","tags":["launch","announcement"]},{"date":"2026-02-15","title":"Beta Release","description":"Our beta release is now available for early testers.","tags":["beta","release"]}]}', 'default', 1, 8, datetime('now'));

-- ============================================================
-- Content Pages (6 rows)
-- ============================================================

INSERT OR REPLACE INTO pages (slug, parent_slug, title, description, content, faqs, related_pages, cover_image, metadata, layout, published, sort_order, updated_at) VALUES
('guides', NULL, 'Guides', 'In-depth guides to help you get the most out of our product and grow your business.',
  '[{"type":"paragraph","text":"Welcome to our guides hub. Whether you are just getting started or looking to master advanced features, we have a guide for you. Browse the topics below and dive into the one that fits your needs."}]',
  '[{"question":"Who are these guides for?","answer":"Our guides are written for founders, marketers, and product teams who want practical, actionable advice they can apply immediately."},{"question":"How often do you publish new guides?","answer":"We add new guides regularly based on user feedback and emerging best practices. Subscribe to the waitlist to get notified when new content drops."},{"question":"Can I request a guide on a specific topic?","answer":"Absolutely. Use our contact form to suggest a topic and we will prioritize it based on demand."}]',
  '[{"title":"About Us","description":"Learn more about our team and mission.","href":"/about"},{"title":"Resources","description":"Tools and downloads to support your workflow.","href":"/resources"}]',
  NULL, NULL, 'pillar', 1, 10, datetime('now')),

('guides/getting-started', 'guides', 'Getting Started Guide', 'Everything you need to know to set up your account and launch your first project.',
  '[{"type":"heading","text":"Getting Started in Three Steps","level":2},{"type":"paragraph","text":"Setting up your account takes less than five minutes. Begin by creating your workspace, inviting your team, and configuring your first project. This guide walks you through each step with screenshots and tips so you can hit the ground running."},{"type":"list","items":["Create your workspace and choose a plan","Invite team members and assign roles","Configure your first project and set milestones"],"ordered":true}]',
  '[{"question":"How long does setup take?","answer":"Most users complete the full setup in under five minutes. If you have a large team, allow an extra few minutes for invitations and role assignments."},{"question":"Can I change my plan later?","answer":"Yes. You can upgrade or downgrade your plan at any time from the billing settings page."}]',
  '[{"title":"Email Marketing Guide","description":"Learn to build effective email campaigns.","href":"/guides/email-marketing"},{"title":"SEO Basics Guide","description":"Improve your search engine rankings.","href":"/guides/seo-basics"}]',
  NULL, NULL, 'default', 1, 11, datetime('now')),

('guides/email-marketing', 'guides', 'Email Marketing Guide', 'Learn how to build, segment, and optimize email campaigns that convert.',
  '[{"type":"heading","text":"Email Marketing That Actually Works","level":2},{"type":"paragraph","text":"Email remains the highest-ROI channel for most businesses, but only when done right. This guide covers list building, segmentation, subject line optimization, and deliverability best practices so your messages land in the inbox and drive action."},{"type":"callout","text":"Companies that segment their email lists see up to 760% more revenue from email campaigns compared to one-size-fits-all blasts.","variant":"info"}]',
  '[{"question":"What is a good open rate?","answer":"Industry averages hover around 20-25%, but well-segmented lists targeting engaged subscribers often exceed 35%."},{"question":"How often should I email my list?","answer":"Start with once a week. Monitor unsubscribe rates and engagement metrics, then adjust frequency based on what your audience responds to."}]',
  '[{"title":"Getting Started Guide","description":"Set up your account and launch your first project.","href":"/guides/getting-started"},{"title":"SEO Basics Guide","description":"Improve your search engine rankings.","href":"/guides/seo-basics"}]',
  NULL, NULL, 'default', 1, 12, datetime('now')),

('guides/seo-basics', 'guides', 'SEO Basics Guide', 'A practical introduction to search engine optimization for founders and marketers.',
  '[{"type":"heading","text":"SEO Fundamentals You Can Apply Today","level":2},{"type":"paragraph","text":"Search engine optimization does not have to be complicated. This guide distills the most impactful practices into a clear framework: technical foundations, on-page optimization, and content strategy. Follow these steps to earn sustainable organic traffic without resorting to shortcuts."},{"type":"list","items":["Ensure your site loads in under 3 seconds on mobile","Write unique title tags and meta descriptions for every page","Build internal links between related content to help search engines understand your site structure"],"ordered":false}]',
  '[{"question":"How long does SEO take to show results?","answer":"Most sites begin seeing measurable improvements within three to six months of consistent effort. Competitive keywords may take longer."},{"question":"Do I need to hire an SEO agency?","answer":"Not necessarily. Many founders see strong results by applying the fundamentals in this guide themselves. An agency can help if you need to scale quickly or compete in a crowded market."}]',
  '[{"title":"Getting Started Guide","description":"Set up your account and launch your first project.","href":"/guides/getting-started"},{"title":"Email Marketing Guide","description":"Learn to build effective email campaigns.","href":"/guides/email-marketing"}]',
  NULL, NULL, 'default', 1, 13, datetime('now')),

('about', NULL, 'About Us', 'Meet the team behind the product and learn what drives us.',
  '[{"type":"heading","text":"Our Story","level":2},{"type":"paragraph","text":"We started this company because we experienced the problem firsthand. After years of cobbling together spreadsheets, half-baked tools, and duct-tape integrations, we decided to build the solution we wished had existed. Our small, distributed team brings experience from companies like Stripe, Vercel, and Shopify."},{"type":"callout","text":"Our mission is to give every founder and small team the same operational advantage that well-funded startups take for granted.","variant":"tip"},{"type":"paragraph","text":"We are based nowhere and everywhere — a fully remote team spanning four time zones. We believe great products are built by people who care deeply about the problem, not by people who happen to sit in the same office."}]',
  '[{"question":"Where is your company based?","answer":"We are a fully remote company with team members across North America and Europe. Our legal entity is incorporated in Delaware."},{"question":"Are you hiring?","answer":"We are always interested in hearing from talented people. Check our careers page or reach out via the contact form."},{"question":"How is the company funded?","answer":"We are bootstrapped and profitable. This means we answer to our customers, not investors."}]',
  '[{"title":"Guides","description":"In-depth guides on product and growth topics.","href":"/guides"},{"title":"Contact","description":"Get in touch with our team.","href":"/contact"}]',
  NULL, NULL, 'landing', 1, 14, datetime('now')),

('resources', NULL, 'Resources', 'Downloadable tools, templates, and reference materials to accelerate your workflow.',
  '[{"type":"paragraph","text":"We have compiled our most useful tools and templates into one place. Whether you need a project planning spreadsheet, an email campaign checklist, or a pitch deck framework, you will find it here. All resources are free to use and regularly updated."}]',
  '[{"question":"Are these resources free?","answer":"Yes, every resource on this page is free to download and use. No signup required."},{"question":"Can I share these with my team?","answer":"Absolutely. All resources are licensed for internal business use. Share them with anyone on your team."}]',
  '[{"title":"Guides","description":"Step-by-step guides for common workflows.","href":"/guides"},{"title":"About Us","description":"Learn more about our team and mission.","href":"/about"}]',
  NULL, NULL, 'listing', 1, 15, datetime('now'));

-- ============================================================
-- Blog Posts (12 posts)
-- ============================================================

INSERT OR REPLACE INTO posts (slug, title, description, content, faqs, cover_image, author, tags, published, published_at, created_at, updated_at) VALUES
-- Post 1: Getting Started with Our Product
('getting-started-with-our-product', 'Getting Started with Our Product', 'A step-by-step walkthrough to help you set up your account, configure your workspace, and launch your first project in under ten minutes.',
  '[{"type":"paragraph","text":"Getting started with a new tool can feel overwhelming, but it does not have to be. We designed our onboarding flow to get you from zero to productive in under ten minutes. This guide walks you through every step so you can focus on the work that matters."},{"type":"heading","text":"Step 1: Create Your Workspace","level":2},{"type":"paragraph","text":"After signing up, the first thing you will see is the workspace creation screen. Choose a name that reflects your team or project. You can always rename it later, but picking something clear from the start helps with organization as you grow."},{"type":"heading","text":"Step 2: Invite Your Team","level":2},{"type":"list","items":["Navigate to Settings and then Team Members","Click Invite and enter email addresses","Assign roles: Admin, Editor, or Viewer","Team members receive an invitation email with a direct login link"],"ordered":true},{"type":"callout","text":"Pro tip: Start with two or three core team members. You can always add more people later once you have established your workflow.","variant":"tip"},{"type":"heading","text":"Step 3: Configure Your First Project","level":2},{"type":"paragraph","text":"Projects are the central organizing unit. Create one for each initiative, product line, or campaign. Set milestones, assign owners, and establish deadlines. The dashboard will track progress automatically."},{"type":"cta","text":"Ready to get started? Join the waitlist and be among the first to try it."}]',
  '[{"question":"Do I need a credit card to sign up?","answer":"No. You can sign up and use the free tier without entering any payment information."},{"question":"Can I import data from another tool?","answer":"Yes. We support CSV imports and direct integrations with several popular project management tools."},{"question":"What if I need help during setup?","answer":"Our support team is available via live chat during business hours, and our help center has detailed guides for every feature."}]',
  NULL, 'Admin', '["getting-started","product","tutorial"]', 1, datetime('now', '-30 days'), datetime('now', '-30 days'), datetime('now', '-30 days')),

-- Post 2: Top 10 Productivity Tips
('top-10-productivity-tips', 'Top 10 Productivity Tips', 'Proven strategies to help you accomplish more meaningful work in less time without burning out.',
  '[{"type":"paragraph","text":"Productivity is not about cramming more tasks into your day. It is about doing the right things with greater focus and less friction. After studying the habits of high-performing founders, engineers, and creators, we distilled the ten most impactful practices into this guide."},{"type":"heading","text":"1. Define Your Top Three Each Morning","level":2},{"type":"paragraph","text":"Before you open your inbox, write down the three outcomes that would make this day a success. Everything else is secondary. This single habit prevents the reactive spiral that derails most workdays."},{"type":"heading","text":"2. Time-Block Deep Work","level":2},{"type":"paragraph","text":"Reserve two-hour blocks on your calendar for focused work. Treat them as non-negotiable meetings with yourself. Disable notifications, close unnecessary tabs, and commit fully."},{"type":"heading","text":"3. Use the Two-Minute Rule","level":2},{"type":"paragraph","text":"If a task takes less than two minutes, do it immediately rather than adding it to a list. This clears mental overhead and keeps small items from piling up."},{"type":"heading","text":"4. Batch Communication","level":2},{"type":"paragraph","text":"Check email and messages at set intervals — say 9 AM, 12 PM, and 4 PM — instead of reacting to every notification in real time."},{"type":"quote","text":"The key is not to prioritize what is on your schedule, but to schedule your priorities. — Stephen Covey"},{"type":"heading","text":"5. Take Real Breaks","level":2},{"type":"paragraph","text":"Step away from your screen every 90 minutes. A short walk, stretching, or even just looking out a window resets your focus and prevents cumulative fatigue."},{"type":"cta","text":"Want a productivity toolkit built for modern teams? Join the waitlist today."}]',
  '[{"question":"How do I stay productive when I feel overwhelmed?","answer":"Start by reducing scope. Pick just one task from your top-three list and commit to finishing it before thinking about anything else. Momentum builds from small wins."},{"question":"Is multitasking ever a good idea?","answer":"Research consistently shows that multitasking reduces the quality and speed of work. Sequential focus on individual tasks almost always produces better results."}]',
  NULL, 'Admin', '["productivity","tips","workflow"]', 1, datetime('now', '-28 days'), datetime('now', '-28 days'), datetime('now', '-28 days')),

-- Post 3: The Future of Remote Work
('future-of-remote-work', 'The Future of Remote Work', 'How distributed teams are reshaping the way we collaborate and what your company needs to do to stay ahead.',
  '[{"type":"paragraph","text":"The shift to remote work was not a temporary experiment. It was a permanent restructuring of how knowledge work gets done. Companies that embrace this reality and invest in the right tools, processes, and culture will have a significant hiring and retention advantage over those clinging to the old model."},{"type":"heading","text":"The Data Is Clear","level":2},{"type":"paragraph","text":"Multiple studies from 2024 and 2025 confirm that remote-friendly companies attract a wider talent pool, report higher employee satisfaction, and often outperform in-office peers on output metrics. The debate is no longer whether remote work is viable — it is how to do it well."},{"type":"table","headers":["Factor","In-Office","Remote / Hybrid"],"rows":[["Talent pool radius","50-mile commute zone","Global"],["Average employee tenure","2.1 years","2.8 years"],["Reported work satisfaction","62%","78%"],["Office cost per employee per year","$12,000","$2,400"]]},{"type":"heading","text":"Keys to Making Remote Work Succeed","level":2},{"type":"list","items":["Default to asynchronous communication so people across time zones can contribute without waiting","Document decisions in writing rather than relying on hallway conversations","Invest in tools that create transparency — shared dashboards, project boards, recorded stand-ups","Schedule intentional social time so remote does not mean isolated"],"ordered":false},{"type":"callout","text":"Our product is designed for distributed teams from the ground up — not bolted on as an afterthought. Async collaboration, real-time visibility, and timezone-aware scheduling are core features.","variant":"info"},{"type":"paragraph","text":"The future belongs to teams that can work effectively regardless of where their members sit. If your tools and processes still assume everyone is in the same room, it is time to upgrade."}]',
  '[{"question":"Is fully remote better than hybrid?","answer":"It depends on the nature of the work and the team. Fully remote works well for companies that invest in async processes. Hybrid can work but requires very intentional scheduling to avoid creating two tiers of employees."},{"question":"How do you build culture in a remote team?","answer":"Culture is built through shared values, consistent communication, and trust — not physical proximity. Regular virtual social events, transparent decision-making, and public recognition go a long way."},{"question":"What tools do remote teams need?","answer":"At minimum: a chat tool, a video meeting tool, a project management system, and a shared documentation platform. The best teams also invest in async video and collaborative whiteboarding."}]',
  NULL, 'Admin', '["remote-work","future","collaboration"]', 1, datetime('now', '-25 days'), datetime('now', '-25 days'), datetime('now', '-25 days')),

-- Post 4: Building Better Habits
('building-better-habits', 'Building Better Habits', 'A practical framework for creating lasting habits that compound into meaningful personal and professional growth.',
  '[{"type":"paragraph","text":"Habits are the compound interest of self-improvement. Small, consistent actions repeated over weeks and months produce results that feel disproportionate to the effort. The challenge is not knowing what to do — it is designing systems that make the right behavior automatic."},{"type":"heading","text":"The Four-Step Habit Loop","level":2},{"type":"list","items":["Cue: Make the trigger for your desired habit obvious and unavoidable","Craving: Pair the habit with something you genuinely enjoy","Response: Reduce friction so the habit takes less than two minutes to start","Reward: Celebrate small wins to reinforce the behavior loop"],"ordered":true},{"type":"heading","text":"Start Embarrassingly Small","level":2},{"type":"paragraph","text":"The biggest mistake people make is trying to overhaul everything at once. Instead, commit to the minimum viable version of the habit. Want to read more? Start with two pages a day. Want to exercise? Start with five push-ups. The goal is consistency, not intensity."},{"type":"callout","text":"Warning: Trying to build more than two new habits simultaneously almost always leads to failure. Focus on one or two until they become automatic, then add more.","variant":"warning"},{"type":"quote","text":"You do not rise to the level of your goals. You fall to the level of your systems. — James Clear"},{"type":"heading","text":"Track and Iterate","level":2},{"type":"paragraph","text":"Use a simple habit tracker — even a checkbox on a calendar works. The visual streak creates its own motivation. Review weekly: What worked? What got in the way? Adjust the system, not the goal."},{"type":"list","items":["Track daily completion with a simple yes or no","Review progress every Sunday evening","Adjust the cue or environment if you miss more than two days in a row","Never miss twice — one bad day is a blip, two is the start of a new pattern"],"ordered":false}]',
  '[{"question":"How long does it take to form a new habit?","answer":"Research suggests it takes an average of 66 days, though this varies widely depending on the complexity of the behavior and the individual. The key is not to fixate on a number but to focus on never missing twice."},{"question":"What should I do when I fall off track?","answer":"Get back on track immediately. Missing once is normal. Missing twice is the start of a new habit. The most important rep is the one right after a miss."},{"question":"Can I break bad habits using the same framework?","answer":"Yes. Invert the four steps: make the cue invisible, the craving unattractive, the response difficult, and the reward unsatisfying. Remove the triggers from your environment whenever possible."}]',
  NULL, 'Admin', '["habits","self-improvement","productivity"]', 1, datetime('now', '-22 days'), datetime('now', '-22 days'), datetime('now', '-22 days')),

-- Post 5: The Art of Deep Work
('the-art-of-deep-work', 'The Art of Deep Work', 'How to cultivate the ability to focus without distraction on cognitively demanding tasks.',
  '[{"type":"paragraph","text":"Deep work is the ability to focus without distraction on a cognitively demanding task. It is the superpower that separates people who produce exceptional results from those who stay busy but never move the needle. In an economy that rewards rare, valuable skills, the ability to do deep work is becoming increasingly important — and increasingly rare."},{"type":"quote","text":"To produce at your peak level you need to work for extended periods with full concentration on a single task free from distraction. — Cal Newport"},{"type":"heading","text":"Why Deep Work Matters More Than Ever","level":2},{"type":"paragraph","text":"The modern workplace is a minefield of distraction. Slack notifications, email threads, social media, and open-plan offices conspire to fragment your attention into tiny, useless shards. Studies show that it takes an average of 23 minutes to fully regain focus after a single interruption. If you are interrupted four times in a morning, you have effectively lost the entire session."},{"type":"heading","text":"Practical Strategies for Deep Work","level":2},{"type":"list","items":["Schedule deep work sessions on your calendar and protect them like you would a meeting with your most important client","Create a physical or digital ritual that signals the start of a deep work session — close all tabs, put on headphones, start a timer","Choose a consistent location where you only do deep work so your brain associates the space with focus","Set a hard stop time to prevent burnout and to create healthy urgency"],"ordered":false},{"type":"callout","text":"Start with just one 90-minute deep work session per day. Most people who try this for the first time are shocked by how much they accomplish compared to a full day of shallow, interrupted work.","variant":"tip"},{"type":"paragraph","text":"Deep work is a skill, not a talent. Like any skill, it improves with deliberate practice. The first few sessions may feel uncomfortable — your brain will crave distraction. Push through. After a few weeks, you will find it easier to enter a state of flow, and the quality of your output will speak for itself."},{"type":"cta","text":"Our product helps teams protect focus time with built-in scheduling and notification controls. Join the waitlist."}]',
  '[{"question":"How is deep work different from just working hard?","answer":"Hard work can be shallow — answering emails, attending meetings, and handling logistics all take effort but do not produce the same caliber of output. Deep work specifically refers to focused, uninterrupted concentration on high-value cognitive tasks."},{"question":"Can I do deep work in an open office?","answer":"It is harder but not impossible. Noise-canceling headphones, a visible do-not-disturb signal, and an agreement with your team about focus hours can create the conditions you need."}]',
  NULL, 'Admin', '["deep-work","focus","productivity"]', 1, datetime('now', '-19 days'), datetime('now', '-19 days'), datetime('now', '-19 days')),

-- Post 6: Email Marketing 101
('email-marketing-101', 'Email Marketing 101', 'A comprehensive guide to building an email list, writing campaigns that convert, and measuring what matters.',
  '[{"type":"paragraph","text":"Email marketing delivers the highest return on investment of any digital marketing channel — roughly $36 for every $1 spent. Yet most companies squander this opportunity with generic blasts, poor segmentation, and subject lines that belong in a spam folder. This guide covers the fundamentals that separate effective email programs from noise."},{"type":"heading","text":"Building Your List the Right Way","level":2},{"type":"paragraph","text":"The foundation of email marketing is a clean, engaged list of people who genuinely want to hear from you. Never buy a list. Instead, earn subscribers by offering something valuable — a useful guide, early access, a discount — in exchange for their email address."},{"type":"list","items":["Place signup forms on high-traffic pages like your homepage, blog, and pricing page","Offer a lead magnet that solves a specific problem your audience faces","Use double opt-in to ensure list quality and compliance","Clean your list quarterly by removing unengaged subscribers"],"ordered":false},{"type":"heading","text":"Anatomy of a High-Converting Email","level":2},{"type":"table","headers":["Element","Best Practice","Common Mistake"],"rows":[["Subject line","Under 50 characters, specific benefit, creates curiosity","Vague or clickbait — leads to opens but not trust"],["Preview text","Complements subject line, adds context","Left as default or repeating the subject"],["Body copy","One clear message, conversational tone, scannable","Walls of text, multiple competing CTAs"],["Call to action","Single, prominent button with action verb","Tiny link buried in a paragraph"],["Unsubscribe link","Visible and easy — legally required","Hidden or requiring login to unsubscribe"]]},{"type":"heading","text":"Metrics That Actually Matter","level":2},{"type":"paragraph","text":"Open rate tells you about your subject lines. Click rate tells you about your content. Conversion rate tells you about your offer. Unsubscribe rate tells you about your frequency and relevance. Track all four, but optimize for conversions — that is where revenue lives."},{"type":"download","downloadUrl":"/uploads/email-marketing-checklist.pdf","downloadLabel":"Download the Email Campaign Checklist"},{"type":"cta","text":"Want to see email marketing in action? Join our waitlist and experience our onboarding sequence firsthand."}]',
  '[{"question":"How often should I send marketing emails?","answer":"Start with once a week. Monitor your unsubscribe rate — if it stays below 0.5%, you can experiment with increasing frequency. If it spikes, pull back."},{"question":"What is a good email open rate?","answer":"Industry averages range from 15-25% depending on the sector. A well-maintained, segmented list should target above 25%."},{"question":"Do I need a dedicated email marketing tool?","answer":"For anything beyond a handful of subscribers, yes. Tools like Resend, ConvertKit, or Mailchimp provide deliverability, automation, and analytics that you cannot replicate manually."}]',
  NULL, 'Admin', '["email","marketing","growth"]', 1, datetime('now', '-16 days'), datetime('now', '-16 days'), datetime('now', '-16 days')),

-- Post 7: How We Built Our MVP
('how-we-built-our-mvp', 'How We Built Our MVP', 'The real story behind our minimum viable product — what we built, what we skipped, and what we learned.',
  '[{"type":"paragraph","text":"Every startup advice article tells you to build an MVP. Very few tell you what that actually looks like in practice — the hard tradeoffs, the features you cut even though you love them, and the terrifying moment you put something unfinished in front of real users. This is our story."},{"type":"heading","text":"Defining the Core Problem","level":2},{"type":"paragraph","text":"Before writing a single line of code, we spent three weeks talking to 40 potential users. The goal was not to validate our solution — it was to deeply understand the problem. We kept hearing the same complaint: existing tools required too much setup and too much maintenance. People wanted something that just worked out of the box."},{"type":"heading","text":"The Three-Week Build Sprint","level":2},{"type":"paragraph","text":"We gave ourselves exactly three weeks to ship a working product. The constraint was intentional — a longer timeline would have invited scope creep. We chose Next.js on Cloudflare Workers for the stack because it let us move fast without worrying about infrastructure scaling."},{"type":"callout","text":"The hardest part of building an MVP is not writing code. It is deciding what not to build. Every feature you add delays the moment you get real feedback, and real feedback is the only thing that matters at this stage.","variant":"info"},{"type":"heading","text":"What We Shipped (and What We Cut)","level":2},{"type":"list","items":["Shipped: Core workflow automation with a single integration point","Shipped: A clean, minimal dashboard that showed progress at a glance","Cut: Custom reporting — we used simple database queries instead","Cut: Team collaboration features — we focused on solo users first","Cut: Mobile app — responsive web was good enough for launch"],"ordered":false},{"type":"heading","text":"What We Learned","level":2},{"type":"paragraph","text":"Users did not care about our rough edges. They cared about whether the tool solved their problem. Two of our most requested features today were things we almost built into the MVP but cut. One of the features we thought was essential turned out to be rarely used. The lesson: your instincts about what matters are probably wrong. Ship, measure, learn."},{"type":"cta","text":"We are building the next version based on everything we learned. Join the waitlist to be part of it."}]',
  '[{"question":"How long did it take to build your MVP?","answer":"Three weeks from first commit to first user. We deliberately constrained the timeline to force prioritization."},{"question":"What tech stack did you use?","answer":"Next.js 16 running on Cloudflare Workers via OpenNext, with D1 for the database and R2 for asset storage. The entire infrastructure costs under $20 per month at our current scale."},{"question":"How many users did you have at launch?","answer":"We launched to a private group of 25 beta testers recruited from our waitlist. Their feedback shaped every major feature decision in the following months."}]',
  NULL, 'Admin', '["startup","mvp","engineering"]', 1, datetime('now', '-13 days'), datetime('now', '-13 days'), datetime('now', '-13 days')),

-- Post 8: Design Principles for Startups
('design-principles-for-startups', 'Design Principles for Startups', 'Six design principles that help early-stage startups build products users actually want to use.',
  '[{"type":"paragraph","text":"You do not need a design team to build a beautiful, usable product. You need a clear set of principles that guide every decision — from button placement to information architecture. These six principles have shaped our product from day one, and they work for any startup willing to take design seriously."},{"type":"heading","text":"1. Clarity Over Cleverness","level":2},{"type":"paragraph","text":"Every element on the screen should communicate its purpose instantly. If a user has to think about what a button does or where a feature lives, you have failed. Use plain language, established patterns, and generous whitespace."},{"type":"heading","text":"2. Reduce Decisions, Not Features","level":2},{"type":"paragraph","text":"Good design does not mean fewer features. It means fewer decisions required to use those features. Sensible defaults, progressive disclosure, and smart automation let you offer powerful functionality without overwhelming the user."},{"type":"heading","text":"3. Design for the Worst Case","level":2},{"type":"list","items":["What does the dashboard look like with zero data?","How does the form behave when the user enters something unexpected?","What happens when the network connection drops mid-action?","How does the layout hold up on a small phone screen?"],"ordered":false},{"type":"callout","text":"The empty state is the first thing a new user sees. If it is confusing or unhelpful, you lose them before they experience your product''s value. Invest more time in empty states than you think is reasonable.","variant":"tip"},{"type":"heading","text":"4. Consistency Beats Novelty","level":2},{"type":"paragraph","text":"Reuse the same components, the same spacing, and the same interaction patterns throughout your product. Novelty in interface design creates cognitive load. Save your creativity for the problems you are solving, not for reinventing the checkbox."},{"type":"quote","text":"Good design is actually a lot harder than you think. It is not just what it looks like. Design is how it works. — Steve Jobs"},{"type":"heading","text":"5. Ship, Observe, Iterate","level":2},{"type":"paragraph","text":"Do not design in a vacuum. Ship something real, watch how people use it through session recordings and analytics, then iterate. Your best design insights will come from watching a real user struggle with something you thought was obvious."}]',
  '[{"question":"Do startups need a full-time designer?","answer":"Not initially. A founder with good taste and a willingness to learn basic design principles can get surprisingly far. Invest in a designer when you have product-market fit and need to scale the experience."},{"question":"What design tools do you recommend for startups?","answer":"Figma for design and prototyping, shadcn/ui or Tailwind UI for component libraries, and Linear or Notion for design system documentation. Keep the tool count low."},{"question":"How do you balance speed with design quality?","answer":"Use a component library from day one. Consistent building blocks let you move fast without accumulating design debt. The initial investment in a design system pays for itself within weeks."}]',
  NULL, 'Admin', '["design","startups","ux"]', 1, datetime('now', '-10 days'), datetime('now', '-10 days'), datetime('now', '-10 days')),

-- Post 9: Understanding Customer Feedback
('understanding-customer-feedback', 'Understanding Customer Feedback', 'How to collect, categorize, and act on customer feedback without drowning in noise.',
  '[{"type":"paragraph","text":"Customer feedback is the most valuable data your company has — and the most misused. Most teams either ignore feedback entirely or try to implement every suggestion, ending up with a bloated product that delights no one. The key is building a structured system that separates signal from noise and ties feedback directly to product decisions."},{"type":"heading","text":"Setting Up Your Feedback Pipeline","level":2},{"type":"paragraph","text":"Feedback arrives through many channels: support tickets, social media, app store reviews, NPS surveys, sales calls, and direct messages. The first step is consolidating all of these into a single, searchable repository. Tag each piece of feedback with the customer segment, the feature area, and the sentiment."},{"type":"table","headers":["Feedback Source","Signal Strength","Volume","Best For"],"rows":[["Customer interviews","Very high","Low","Understanding root problems"],["Support tickets","High","Medium","Identifying bugs and friction"],["NPS / surveys","Medium","High","Tracking trends over time"],["Social media","Low-medium","High","Gauging public sentiment"],["App store reviews","Medium","Medium","Competitive positioning"]]},{"type":"heading","text":"The ICE Framework for Prioritization","level":2},{"type":"list","items":["Impact: How many customers does this affect, and how severely?","Confidence: How certain are we that this change will solve the problem?","Effort: How much engineering and design time will this require?"],"ordered":true},{"type":"callout","text":"Beware of the loudest-voice bias. A single passionate user requesting a feature does not mean it is a priority. Always cross-reference individual requests against aggregate data before committing resources.","variant":"warning"},{"type":"paragraph","text":"Review your feedback backlog weekly with the product team. Look for themes, not individual requests. If fifteen users describe the same pain point in different words, that is a clear signal. If one user has an elaborate feature idea, that is an opinion worth noting but not acting on immediately."},{"type":"cta","text":"Our product includes a built-in feedback collection tool. Join the waitlist to see it in action."}]',
  '[{"question":"How do you handle conflicting feedback?","answer":"Conflicting feedback usually means you have multiple user segments with different needs. Segment your feedback by persona or use case, then evaluate each group''s requests independently. You may need different solutions for different segments."},{"question":"How quickly should we respond to feedback?","answer":"Acknowledge receipt within 24 hours. You do not need to resolve the issue immediately, but people need to know they were heard. A simple reply saying you have logged their feedback goes a long way."},{"question":"What if customers ask for features we will never build?","answer":"Be honest and transparent. Explain your reasoning briefly and, if possible, suggest a workaround or an alternative tool that meets their need. Customers respect candor more than vague promises."}]',
  NULL, 'Admin', '["feedback","customers","product"]', 1, datetime('now', '-7 days'), datetime('now', '-7 days'), datetime('now', '-7 days')),

-- Post 10: Year in Review 2025
('year-in-review-2025', 'Year in Review: 2025', 'A look back at what we accomplished in 2025 — the milestones, the lessons, and what comes next.',
  '[{"type":"paragraph","text":"As we close the book on 2025, we want to share an honest look at what we accomplished, where we fell short, and what we are excited about heading into the new year. Transparency is one of our core values, and that extends to how we talk about our own progress."},{"type":"heading","text":"Key Milestones","level":2},{"type":"list","items":["Launched our MVP to the first 25 beta testers in March","Grew the waitlist to over 5,000 signups by June","Shipped 47 product updates based on user feedback","Expanded the team from 2 to 5 people","Achieved profitability in November — no external funding needed"],"ordered":false},{"type":"heading","text":"What Went Well","level":2},{"type":"paragraph","text":"Our decision to launch early and iterate based on real feedback was vindicated. The features users loved most were not the ones we expected. By staying close to our beta testers and shipping weekly, we built something genuinely useful rather than something theoretically impressive."},{"type":"heading","text":"Where We Fell Short","level":2},{"type":"paragraph","text":"Documentation lagged behind feature development. Our onboarding flow had too many steps. We underestimated the importance of mobile performance and had to do a significant refactor in Q3. These are all fixable, but they cost us time and some early user goodwill."},{"type":"heading","text":"Looking Ahead to 2026","level":2},{"type":"paragraph","text":"This year is about scaling what works. We are investing heavily in team collaboration features, a redesigned dashboard, and a public API. We are also doubling our content output to help users get more value from the product."},{"type":"cta","text":"Want to be part of the journey? Join our waitlist and get early access to everything we ship in 2026."}]',
  '[{"question":"Is the product available to the public yet?","answer":"We are currently in a limited beta with a growing group of users. Join the waitlist to secure your spot — we are opening access in waves throughout early 2026."},{"question":"How is the company funded?","answer":"We are fully bootstrapped and became profitable in November 2025. This means we can focus entirely on building what our users need without pressure from investors."}]',
  NULL, 'Admin', '["review","company","milestones"]', 1, datetime('now', '-5 days'), datetime('now', '-5 days'), datetime('now', '-5 days')),

-- Post 11: Interview with Our CTO
('interview-with-our-cto', 'Interview with Our CTO', 'A candid conversation with our CTO about technical decisions, engineering culture, and the road ahead.',
  '[{"type":"paragraph","text":"We sat down with our CTO to talk about the technical decisions that shaped our product, what it is like to build an engineering team from scratch, and where the technology is heading. The conversation was wide-ranging and candid — here are the highlights."},{"type":"heading","text":"On Choosing the Tech Stack","level":2},{"type":"quote","text":"We picked Cloudflare Workers and D1 because we wanted to be as close to the edge as possible. When your entire application runs within milliseconds of the user, you eliminate an entire category of performance problems. The tradeoff is that you have to think differently about state and storage, but that constraint actually leads to better architecture."},{"type":"paragraph","text":"The decision to use Next.js on Workers via OpenNext was driven by pragmatism. The React ecosystem gives us access to the largest pool of frontend talent and the richest component ecosystem. OpenNext lets us deploy it on Cloudflare without sacrificing any Next.js features."},{"type":"heading","text":"On Engineering Culture","level":2},{"type":"quote","text":"I hire for curiosity and ownership. If someone needs to be told exactly what to do, this is not the right environment. Our engineers own features end-to-end — from database schema to UI polish. That level of ownership is not for everyone, but the people who thrive here produce extraordinary work."},{"type":"callout","text":"Our entire engineering team works asynchronously across four time zones. Every technical decision is documented in an ADR (Architecture Decision Record) so anyone can understand the reasoning behind past choices without scheduling a meeting.","variant":"info"},{"type":"heading","text":"On the Road Ahead","level":2},{"type":"paragraph","text":"When asked about what excites them most about the next twelve months, our CTO pointed to two areas: real-time collaboration features powered by Durable Objects, and an AI-assisted workflow engine that can automate repetitive tasks based on patterns it observes in user behavior."},{"type":"paragraph","text":"The interview wrapped with a piece of advice for technical founders: choose boring technology for your infrastructure and save your innovation budget for the product itself. Your users do not care what database you use. They care that the product works reliably and helps them get things done."}]',
  '[{"question":"What programming languages does your team use?","answer":"TypeScript everywhere — frontend, backend, infrastructure-as-code, and tests. Using a single language across the stack eliminates context switching and makes it easier for anyone on the team to contribute to any part of the codebase."},{"question":"Are you hiring engineers?","answer":"We are always interested in talking to strong engineers, especially those with experience in edge computing, real-time systems, or developer tools. Reach out via our contact page."},{"question":"How do you handle on-call and incidents?","answer":"We rotate on-call weekly across the engineering team. Every incident triggers a blameless post-mortem within 48 hours. We track mean time to detection and mean time to resolution as our primary reliability metrics."}]',
  NULL, 'Admin', '["interview","team","engineering"]', 1, datetime('now', '-3 days'), datetime('now', '-3 days'), datetime('now', '-3 days')),

-- Post 12: Five Tools Every Founder Needs
('five-tools-every-founder-needs', 'Five Tools Every Founder Needs', 'A curated list of the tools that save founders the most time and money in the early stages of building a company.',
  '[{"type":"paragraph","text":"In the early days of a startup, every dollar and every hour counts. The tools you choose can either accelerate your progress or drain your resources. After talking to hundreds of founders and running our own company, we have identified the five categories of tools that deliver the most leverage — and our top picks in each."},{"type":"heading","text":"1. Project Management: Linear","level":2},{"type":"paragraph","text":"Linear has become the default project management tool for startups, and for good reason. It is fast, opinionated, and designed for engineering teams. The keyboard-first interface means you spend less time managing work and more time doing it. Unlike bloated alternatives, Linear gets out of your way."},{"type":"heading","text":"2. Communication: Slack (with Discipline)","level":2},{"type":"paragraph","text":"Slack is powerful but dangerous. Without guardrails, it becomes a productivity sink. The trick is to establish norms: use channels, not DMs, for anything work-related. Set expectations about response times. Turn off notifications during focus hours. Slack is a great tool for teams that use it intentionally."},{"type":"heading","text":"3. Documentation: Notion","level":2},{"type":"paragraph","text":"Your company''s knowledge base is one of its most valuable assets. Notion provides a flexible workspace for documentation, meeting notes, wikis, and lightweight databases. Start with a simple structure — an engineering wiki, a product specs folder, and a decision log — and expand as needed."},{"type":"heading","text":"4. Analytics: PostHog","level":2},{"type":"paragraph","text":"Understanding how users interact with your product is non-negotiable. PostHog gives you event tracking, session recordings, feature flags, and A/B testing in a single open-source platform. The free tier is generous enough for most startups through their first year."},{"type":"heading","text":"5. Deployment: Cloudflare","level":2},{"type":"paragraph","text":"Cloudflare''s developer platform — Workers, Pages, D1, R2, Queues — gives startups enterprise-grade infrastructure at startup-friendly prices. Deploy globally in seconds, pay only for what you use, and stop worrying about scaling. It is the closest thing to infrastructure that just works."},{"type":"table","headers":["Category","Tool","Free Tier","Paid Starting At"],"rows":[["Project management","Linear","Up to 250 issues","$8/user/month"],["Communication","Slack","90-day history","$7.25/user/month"],["Documentation","Notion","Personal use","$8/user/month"],["Analytics","PostHog","1M events/month","Usage-based"],["Deployment","Cloudflare","100K requests/day","$5/month"]]},{"type":"download","downloadUrl":"/uploads/founder-toolkit-comparison.pdf","downloadLabel":"Download the Full Toolkit Comparison Sheet"}]',
  '[{"question":"Why not just use free tools?","answer":"Free tools are fine to start, but they often lack features you will need as you grow — advanced permissions, integrations, support SLAs. Choose tools with generous free tiers and clear upgrade paths so you are not forced to migrate later."},{"question":"How much should a startup spend on tools?","answer":"A good rule of thumb is under $50 per person per month for your core stack. If you are spending significantly more than that in the early stages, you are probably over-tooled."},{"question":"What about all-in-one platforms?","answer":"All-in-one tools trade depth for breadth. They are convenient but rarely best-in-class at anything. For early-stage startups where every tool needs to earn its place, we recommend best-of-breed picks in each category."}]',
  NULL, 'Admin', '["tools","founders","startup"]', 1, datetime('now', '-1 days'), datetime('now', '-1 days'), datetime('now', '-1 days'));

-- ============================================================
-- Test Subscribers (5 rows)
-- Clean up first to ensure consistent autoincrement IDs on re-runs
-- ============================================================

DELETE FROM giveaway_actions;
DELETE FROM giveaway_entries;
DELETE FROM subscribers;
DELETE FROM sqlite_sequence WHERE name IN ('subscribers', 'giveaway_entries', 'giveaway_actions');

INSERT INTO subscribers (email, name, referral_code, referred_by, referral_count, position, status, created_at) VALUES
('alice@example.com', 'Alice Johnson', 'abc123', NULL, 2, 1, 'active', datetime('now', '-10 days')),
('bob@example.com', 'Bob Smith', 'def456', 'abc123', 0, 2, 'active', datetime('now', '-9 days')),
('carol@example.com', 'Carol Williams', 'ghi789', 'abc123', 1, 3, 'active', datetime('now', '-8 days')),
('dave@example.com', 'Dave Brown', 'jkl012', 'ghi789', 0, 4, 'active', datetime('now', '-7 days')),
('eve@example.com', 'Eve Davis', 'mno345', NULL, 0, 5, 'unsubscribed', datetime('now', '-6 days'));

-- ============================================================
-- Giveaway Entries (2 rows)
-- ============================================================

INSERT INTO giveaway_entries (email, subscriber_id, total_entries, created_at) VALUES
('alice@example.com', 1, 6, datetime('now', '-5 days')),
('bob@example.com', 2, 1, datetime('now', '-4 days'));

-- ============================================================
-- Giveaway Actions (for Alice)
-- ============================================================

INSERT INTO giveaway_actions (entry_id, action, bonus_entries, metadata, completed_at) VALUES
(1, 'twitter_share', 3, '{"tweetUrl":"https://twitter.com/alice/status/123"}', datetime('now', '-5 days')),
(1, 'twitter_follow', 2, NULL, datetime('now', '-4 days'));
