import type { ThemeSettings } from "@/types/site-settings";

export const themePresets: Record<string, ThemeSettings> = {
	minimal: {
		preset: "minimal",
		accentColor: "#1a1a1a",
		borderRadius: "0.375rem",
		headingWeight: "600",
		fontFamily: "geist",
		heroVariant: "centered",
		headerVariant: "solid",
		footerVariant: "simple",
		postCardVariant: "minimal",
		ctaSectionVariant: "outlined",
	},
	bold: {
		preset: "bold",
		accentColor: "#9747ff",
		borderRadius: "0.625rem",
		headingWeight: "400",
		fontFamily: "inter",
		heroVariant: "gradient",
		headerVariant: "blur",
		footerVariant: "simple",
		postCardVariant: "bordered",
		ctaSectionVariant: "gradient",
	},
	corporate: {
		preset: "corporate",
		accentColor: "#2563eb",
		borderRadius: "0.375rem",
		headingWeight: "600",
		fontFamily: "inter",
		heroVariant: "centered",
		headerVariant: "blur",
		footerVariant: "columns",
		postCardVariant: "bordered",
		ctaSectionVariant: "solid",
	},
	playful: {
		preset: "playful",
		accentColor: "#f97316",
		borderRadius: "9999px",
		headingWeight: "700",
		fontFamily: "dm-sans",
		heroVariant: "gradient",
		headerVariant: "transparent",
		footerVariant: "simple",
		postCardVariant: "filled",
		ctaSectionVariant: "gradient",
	},
};
